/* khyzr design system — the React primitives, built from web/components/*.jsx.
   Generated by web-design-system/site/build.py; do not edit. Needs React 18 on window. */
(function () {
var ns = (window.KhyzrComponents = window.KhyzrComponents || {});
// actions/Button.jsx
(function () {
function Button({ variant = 'primary', size = 'm', href, onClick, disabled, children }) {
  const [hover, setHover] = React.useState(false);
  const pad = size === 'l' ? '15px 30px' : '11px 22px';
  const fs = size === 'l' ? 15.5 : 14;
  const looks = {
    primary: { background: 'var(--ink)', color: '#fff', border: '1px solid var(--ink)' },
    white:   { background: '#fff', color: 'var(--ink)', border: '1px solid #fff' },
    ghost:   { background: 'transparent', color: '#fff', border: '1px solid rgba(255,255,255,.28)' }
  };
  const style = {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8,
    fontFamily: 'var(--font-text)', fontWeight: 600, fontSize: fs, lineHeight: 1,
    padding: pad, borderRadius: 'var(--radius-pill)', cursor: disabled ? 'default' : 'pointer',
    textDecoration: 'none', boxSizing: 'border-box', userSelect: 'none',
    opacity: disabled ? .45 : 1, pointerEvents: disabled ? 'none' : 'auto',
    transform: hover && !disabled ? 'scale(1.05)' : 'scale(1)',
    transition: 'transform var(--dur-hover, 500ms) var(--ease-pop, ease)',
    ...looks[variant] || looks.primary
  };
  const props = { style, onClick, onMouseEnter: () => setHover(true), onMouseLeave: () => setHover(false) };
  return href ? React.createElement('a', { href, ...props }, children) : React.createElement('button', { type: 'button', disabled, ...props, style: { ...style, appearance: 'none' } }, children);
}
ns.Button = Button;
})();
// display/Badge.jsx
(function () {
function Badge({ tone = 'outline', children }) {
  const looks = {
    solid:   { color: '#fff', background: 'var(--link)', border: '1px solid var(--link)' },
    outline: { color: 'var(--link)', background: 'transparent', border: '1px solid #cfe3d6' },
    neutral: { color: 'var(--faint)', background: 'transparent', border: '1px solid var(--hairline)' },
    mint:    { color: 'var(--deep-forest)', background: 'var(--green-100)', border: '1px solid var(--green-100)' }
  };
  return React.createElement('span', { style: {
    ...looks[tone] || looks.outline, display: 'inline-flex', alignItems: 'center',
    fontFamily: 'var(--font-mono)', fontSize: 9.5, letterSpacing: '.16em', textTransform: 'uppercase',
    borderRadius: 'var(--radius-pill)', padding: '3px 9px', lineHeight: 1.4
  } }, children);
}
ns.Badge = Badge;
})();
// display/Eyebrow.jsx
(function () {
function Eyebrow({ num, children, onDark }) {
  return React.createElement('p', { style: {
    margin: 0, fontFamily: 'var(--font-mono)', fontSize: 'var(--text-eyebrow, 12px)',
    letterSpacing: 'var(--tracking-eyebrow, .24em)', textTransform: 'uppercase',
    color: onDark ? '#91BC91' : 'var(--faint)', display: 'inline-flex', alignItems: 'center', gap: '.85ch'
  } },
    React.createElement('span', { style: { width: 24, height: 1, background: onDark ? '#91BC91' : 'var(--khyzr-green)' } }),
    num ? num + ' · ' + children : children
  );
}
ns.Eyebrow = Eyebrow;
})();
// display/ProofStat.jsx
(function () {
function ProofStat({ value, suffix, label, onDark }) {
  return React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: 6, fontFamily: 'var(--font-text)' } },
    React.createElement('div', { style: { display: 'flex', alignItems: 'baseline', gap: 4 } },
      React.createElement('span', { style: { fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 52, letterSpacing: '-.03em', lineHeight: 1, color: onDark ? '#fff' : 'var(--deep-forest)', fontVariantNumeric: 'tabular-nums' } }, value),
      suffix && React.createElement('span', { style: { fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 28, color: onDark ? '#91BC91' : 'var(--khyzr-green)' } }, suffix)
    ),
    label && React.createElement('span', { style: { fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '.14em', textTransform: 'uppercase', color: onDark ? '#8D948F' : 'var(--faint)' } }, label)
  );
}
ns.ProofStat = ProofStat;
})();
// forms/PlateField.jsx
(function () {
function PlateField({ label, helper, error, textarea, onDark, placeholder, value, onChange, disabled, type = 'text', rows = 4 }) {
  const [focus, setFocus] = React.useState(false);
  const base = onDark ? {
    background: focus ? 'rgba(255,255,255,.12)' : 'rgba(255,255,255,.08)',
    border: '1px solid ' + (error ? '#E08A80' : focus ? '#91BC91' : 'transparent'),
    color: '#fff'
  } : {
    background: error ? 'rgba(178,80,70,.06)' : focus ? '#fff' : 'var(--surface-2)',
    border: '1px solid ' + (error ? 'var(--error)' : focus ? 'var(--khyzr-green)' : 'transparent'),
    color: 'var(--body)',
    boxShadow: focus ? '0 0 0 3px rgba(10,105,10,.14)' : 'none'
  };
  const field = {
    ...base, width: '100%', boxSizing: 'border-box', borderRadius: 14, padding: '13px 16px',
    fontFamily: 'var(--font-text)', fontSize: 15, lineHeight: 1.45, outline: 'none',
    transition: 'background .2s ease, border-color .2s ease, box-shadow .2s ease', resize: 'vertical'
  };
  const el = React.createElement(textarea ? 'textarea' : 'input', {
    style: field, placeholder, value, disabled,
    ...(textarea ? { rows } : { type }),
    onChange: onChange ? (e) => onChange(e.target.value) : undefined,
    onFocus: () => setFocus(true), onBlur: () => setFocus(false)
  });
  return React.createElement('label', { style: { display: 'flex', flexDirection: 'column', gap: 7, opacity: disabled ? .45 : 1, fontFamily: 'var(--font-text)' } },
    label && React.createElement('span', { style: { fontSize: 13, fontWeight: 600, color: onDark ? '#EEF2EE' : 'var(--body)' } }, label),
    el,
    (error || helper) && React.createElement('span', { style: { fontSize: 12.5, color: error ? (onDark ? '#E08A80' : 'var(--error)') : (onDark ? '#8D948F' : 'var(--faint)') } }, error || helper)
  );
}
ns.PlateField = PlateField;
})();
})();
